### ISSUE TITLE
As a tutor, I can see a list of all my course assignment (past and present)

### ISSUE THREAD

**Issue by qiandrew** [ucsb-cs56-w20/open-lab-scheduler#32]
Acceptance criteria:
- [x] Be able to select or log in to the profile of a specific tutor.
- [x] Be able to see all my past and present course assignments
- [x] Be able to see what quarter each course assignment was from.

**Comment by AaronHuanger** [comment]
Currently the tutor assignment page only displays which tutors were assigned to a specific class to a specific tutor by listing all the tutors and using a checkbox to mark who was assigned to the course. 

tutorAssignment.html should be changed so that it caters more to an individual tutor.
*title changed from "CS56 Tutor Assignment"  to "Your Assignments" 
*using thymeleaf to automatically create a table that displays all of the tutor's assignments for a quarter in manage.html
*maybe create a data structure in Tutor.java that stores all the tutor's assignments, thus making it easier to find all the tutor's assignments. 
*alternatively (if possible in thymeleaf) make a for loop in manage.html that goes through a list of available time slots for a quarter and displays availability that is associated with the logged in user.
*If the quarter and year is "present", then tutor should be able to edit his/her availability. Can be done by adding buttons that allow the tutor to remove the assignment or by adding a clickable text that redirects the tutor to the open-lab editing page.

Additional Functions
* display assignment by whole academic year
* display assignment by quarter
* display assignment by a specific course 
* display all assignments onto a calendar. //may require adding a calendar plugin 
* assignments displayed on calendar becomes clickable. 
can be done by editing tutorAssignment.html so that these additional options are possible. Alternatively make a new html page displaying these options. Options are clickable texts that link to different html pages that display the appropriate information. To make it easier to find information, maybe implement hashtable in Tutor.java where the key is the courseId and the following
