### ISSUE TITLE
CRUD operations for instructors, (ADMIN ONLY)

### ISSUE THREAD

**Issue by qiandrew** [ucsb-cs56-w20/open-lab-scheduler#36]
- [ ] create: create new instructor and create button

- [ ] read: display instructors allowed to interact in a table. This table is on site on protected endpoint /instructors that only admins can access

- [ ] update: admin are able to update instructor information with an update button

- [ ] delete: able to delete the object with a delete button

- [ ] this is on an instructor webpage that instructors can access

**Comment by jianghuawang** [comment]
We need to add 3 or more buttons including update, delete and create in the HTML files, and these will only the buttons' shapes, so we also need to add some functions like create instructor, update instructor insides AdminController.java file and annotate them properly and specify endpoints.

**Comment by pconrad** [comment]
@gbaroni888 @qiandrew @Ulramok 

I wonder whether this issue should be done.   As I commented on @gbaroni888 's pull request, adding a separate instructor table actually introduces extra complexity that puts us *behind* rather than moves us towards minimum viable product.

I'd rather just see the access to the instructor function driven by the presence of the user's email in the courseOffering table.   The courseOffering table already has the emails for instructors, and that's all we really need to implement the function needed, which is the ability, as an instructor to see a view that represents only my own courses... i.e. the tutors for those courses, and the open lab hours for the tutors in my courses.

Additionally, I might the ability to add and delete tutors for my course, and/or change their types, and or change their assignments.    

But none of that requires having a separate instructor table.. and having that table probably just makes all of those *needed* features more complicated.   And having to do CRUD operations for a new table delays us adding the features that we really do need.

What do you think?

**Comment by zsisco** [comment]
Good points, Prof. Conrad. I spoke with the current assignees on this issue, and we agreed to pull this one back and focus on #39 instead, since that delivers more value. Closing for now.
