### ISSUE TITLE
As an instructor I should be able to create courses in the  course offering table.

### ISSUE THREAD

**Issue by JamesSchwellenbach** [ucsb-cs56-w20/open-lab-scheduler#60]
As an instructor, I can create new course offerings so that there will be a new course in the table.

**Comment by DylanLin29** [comment]
Probably first we have to add all the instructors' emails to the login information in the application so that after the instructor logged in, they have the ability to create the courses in the scheduler. Only when the instructors or the admins log in the scheduler, there will be a place on the website for the them to enter the courses' information. After the instructor click "create", this information can update the properties of a class in the java code and these properties are linked to the HTML file in the application so that the updated information can be reflected on the website.
